# Generated by Django 3.1.2 on 2020-10-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200930_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(upload_to='actors/', verbose_name='Изображение'),
        ),
    ]
